export enum ActionTypes {
  SOCKET_CONNECT = "SOCKET_CONNECT",
  CREATE_GAME = "CREATE_GAME",
  JOIN_GAME = "JOIN_GAME",
  LEAVE_GAME = "LEAVE_GAME",
  REVEAL_SQUARE = "REVEAL_SQUARE",
  REFRESH_GRID = "REFRESH_GRID",
}
